name: Docker

on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/docker.yaml
    - '**/Dockerfile'
    - '**/docker-entrypoint.sh'

jobs:

  build-1.9:

    name: Build 1.9
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build .
      working-dir: 1.9

  build-1.10:

    name: Build 1.10
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build .
      working-dir: 1.10

  build-2.0:

    name: Build 2.0
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build 2.0
      working-dir: 2.0
