name: Docker - v1

on:
  push:
    paths:
    - .github/workflows/v1.yaml
    - '1.10/**'

env:
  AWS_REGION: us-east-1
  ECR_REPO: public.ecr.aws/u0u1j5s3/composer

jobs:
  build:
    name: Build v1.10
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: '1.10'
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        docker build \
        --pull \
        --no-cache \
        --tag composer/composer:1 \
        --tag composer/composer:$(grep -oP 'COMPOSER_VERSION 1.10.\d+' Dockerfile | grep -oP '1.10.\d+') \
        .
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push tag(s) to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker push composer/composer:1
        docker push composer/composer:$(grep -oP 'COMPOSER_VERSION 1.10.\d+' Dockerfile | grep -oP '1.10.\d+')
    - name: Login to Amazon Public ECR
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ECR_ACCESS_KEY }}
        password: ${{ secrets.AWS_ECR_SECRET_KEY }}
    - name: Push tag(s) to Amazon Public ECR
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag composer/composer:1 $ECR_REPO:1
        docker tag composer/composer:$(grep -oP 'COMPOSER_VERSION 1.10.\d+' Dockerfile | grep -oP '1.10.\d+') $ECR_REPO:$(grep -oP 'COMPOSER_VERSION 1.10.\d+' Dockerfile | grep -oP '1.10.\d+')
        docker push $ECR_REPO:1
        docker push $ECR_REPO:$(grep -oP 'COMPOSER_VERSION 1.10.\d+' Dockerfile | grep -oP '1.10.\d+')
